---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: mrsixw/concourse-rsync-resource
    tag: latest
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/stevesmatts/concourse-pipelines.git
    branch: master
- name: go-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: buildpacks
    product_version: Go.*\d+\.\d+\.\d+
- name: transfer-buildpacks
  type: rsync-resource
  source:
    server: ((rsync_server))
    base_dir: /data/repo/buildpacks
    user : ((rsync_user))
    private_key: ((rsync_key))
    disable_version_path: true
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-buildpacks
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: go-buildpack
      trigger: true
    - task: fetch-buidpacks
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: go-buildpack
          path: incoming-buildpacks
        outputs:
        - name: buildpacks
        run:
          path: pipelines-repo/scripts/copy-buidpacks.sh
          args:
          - incoming-buildpacks
          - buildpacks
    - put: transfer-buildpacks
      params: {
        "sync_dir" : "buildpacks",
        "rsync_opts" : ["-Pav", "--ignore-existing"]
      }
    on_failure:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":skull_and_crossbones:"
        text: $BUILD_JOB_NAME job failed
    on_success:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":thumbsup:"
        text: $BUILD_JOB_NAME job succeeded