---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: dotnet-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: dotnet-core-buildpack
- name: binary-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: binary-buildpack
- name: go-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: go-buildpack
- name: java-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: java-buildpack
- name: nodejs-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: nodejs-buildpack
- name: php-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: php-buildpack
- name: python-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: python-buildpack
- name: ruby-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ruby-buildpack
- name: staticfile-buildpack
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: staticfile-buildpack
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-buildpacks
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: dotnet-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: binary-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: go-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: java-buildpack
      trigger: true
      params:
        globs: ["*offline*.zip"]
    - get: nodejs-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: php-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: python-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: ruby-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - get: staticfile-buildpack
      trigger: true
      params:
        globs: ["*cflinuxfs2*.zip"]
    - task: collect-buildpacks
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: dotnet-buildpack
        - name: binary-buildpack
        - name: go-buildpack
        - name: java-buildpack
        - name: nodejs-buildpack
        - name: php-buildpack
        - name: python-buildpack
        - name: ruby-buildpack
        - name: staticfile-buildpack
        outputs:
        - name: outgoing-artifacts
        run:
          path: pipelines-repo/scripts/process-buildpacks.sh
          args:
          - outgoing-artifacts
    - task: transfer-artifacts
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: outgoing-artifacts
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - outgoing-artifacts
          - /data/repo/buildpacks
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Buildpack releases
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed new Buildpack releases
