---
resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier
- name: rsync
  type: docker-image
  source:
    repository: trecnoc/rsync-resource

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines-tasks.git
    branch: master
- name: binary-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: binary-buildpack
    access_token: ((github_access_token))
- name: dotnet-core-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: dotnet-core-buildpack
    access_token: ((github_access_token))
- name: go-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: go-buildpack
    access_token: ((github_access_token))
- name: java-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: java-buildpack
    access_token: ((github_access_token))
- name: nginx-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: nginx-buildpack
    access_token: ((github_access_token))
- name: nodejs-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: nodejs-buildpack
    access_token: ((github_access_token))
- name: php-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: php-buildpack
    access_token: ((github_access_token))
- name: python-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: python-buildpack
    access_token: ((github_access_token))
- name: r-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: r-buildpack
    access_token: ((github_access_token))
- name: ruby-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: ruby-buildpack
    access_token: ((github_access_token))
- name: staticfile-buildpack
  type: github-release
  source:
    owner: cloudfoundry
    repository: staticfile-buildpack
    access_token: ((github_access_token))
- name: mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/buildpacks
- name: notify
  type: slack-notifier
  source:
    url: ((slack_hook))
    disabled: ((slack_disabled))

jobs:
- name: package-binary-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: binary-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-binary-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: binary-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-dotnet-core-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: dotnet-core-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-dotnet-core-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: dotnet-core-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-go-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: go-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-go-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: go-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-java-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: java-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-java-buildpack
    file: pipeline-tasks/package-cached-java-buildpack.yml
    input_mapping:
      buildpack-release: java-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-nginx-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: nginx-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-nginx-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: nginx-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-nodejs-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: nodejs-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-nodejs-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: nodejs-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-php-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: php-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-php-buildpack
    file: pipeline-tasks/package-cached-php-buildpack.yml
    input_mapping:
      buildpack-release: php-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-python-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: python-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-python-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: python-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-r-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: r-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-r-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: r-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-ruby-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: ruby-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-ruby-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: ruby-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: package-staticfile-buildpack
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: staticfile-buildpack
      trigger: true
      params:
        include_source_tarball: true
        globs:
          - NO_MATCH_GLOB
  - task: package-staticfile-buildpack
    file: pipeline-tasks/package-cached-buildpack.yml
    input_mapping:
      buildpack-release: staticfile-buildpack
  - put: mirror
    params:
      sub_dir: buildpack
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
