---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: mrsixw/concourse-rsync-resource
    tag: latest
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/stevesmatts/concourse-pipelines.git
    branch: master
- name: cf-deployment-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    tag_filter: v*
- name: transfer-releases
  type: rsync-resource
  source:
    server: ((rsync_server))
    base_dir: /data/repo/bosh/release
    user : ((rsync_user))
    private_key: ((rsync_key))
    disable_version_path: true
- name: transfer-stemcells
  type: rsync-resource
  source:
    server: ((rsync_server))
    base_dir: /data/repo/bosh_io_stemcells
    user : ((rsync_user))
    private_key: ((rsync_key))
    disable_version_path: true
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-cf
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-deployment-repo
      trigger: true
    - task: fetch-cf
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-deployment-repo
          path: incoming-repo
        outputs:
        - name: release
        - name: stemcells
        run:
          path: pipelines-repo/scripts/process-cf-repo-update.sh
          args:
          - incoming-repo
          - release
          - pipelines-repo/scripts/fetch-bosh-releases-from-manifest.sh
          - pipelines-repo/scripts/ops_files
          - stemcells
    - put: transfer-releases
      params: {
        "sync_dir": "release",
        "rsync_opts": ["-Pav", "--ignore-existing"]
      }
    - put: transfer-stemcells
      params: {
        "sync_dir": "stemcells",
        "rsync_opts": ["-Pav", "--ignore-existing"]
      }
    on_failure:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":skull_and_crossbones:"
        text: $BUILD_JOB_NAME job failed
    on_success:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":thumbsup:"
        text: $BUILD_JOB_NAME job succeeded