---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: cf-cli-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: cli
    access_token: ((github_access_token))
- name: antifreeze-release
  type: github-release
  source:
    owner: odlp
    repository: antifreeze
    access_token: ((github_access_token))
- name: autopilot-release
  type: github-release
  source:
    owner: contraband
    repository: autopilot
    access_token: ((github_access_token))
- name: cf-bpck-mngt-release
  type: github-release
  source:
    owner: davidehringer
    repository: cf-buildpack-management-plugin
    access_token: ((github_access_token))
- name: cf-top-release
  type: github-release
  source:
    owner: ECSTeam
    repository: cloudfoundry-top-plugin
    access_token: ((github_access_token))
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-cf-cli
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-cli-release
      trigger: true
    - get: antifreeze-release
      trigger: true
      params:
        globs:
          - antifreeze-linux
          - antifreeze.exe
    - get: autopilot-release
      trigger: true
      params:
        globs:
          - autopilot-linux
          - autopilot.exe
    - get: cf-bpck-mngt-release
      trigger: true
      params:
        globs:
          - cf-buildpack-management-plugin_linux_amd64
          - cf-buildpack-management-plugin_windows_amd64.exe
    - get: cf-top-release
      trigger: true
      params:
        globs:
          - top-plugin-linux64
          - top-plugin64.exe
    - task: process-cf-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-cli-release
        - name: antifreeze-release
        - name: autopilot-release
        - name: cf-bpck-mngt-release
        - name: cf-top-release
        outputs:
        - name: cf-cli
        run:
          path: pipelines-repo/scripts/process-cf-cli.sh
          args:
          - pipelines-repo/scripts/copy-github-release.sh
          - cf-cli
          - cf-cli-release
          - antifreeze-release
          - autopilot-release
          - cf-bpck-mngt-release
          - cf-top-release
    - task: transfer-cf-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: cf-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - cf-cli
          - /data/repo/cf_cli
    on_failure:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":skull_and_crossbones:"
        text: $BUILD_JOB_NAME job failed
    on_success:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":thumbsup:"
        text: $BUILD_JOB_NAME job succeeded