---
resource_types:
- name: slack-notifier
  type: registry-image
  source:
    repository: mockersf/concourse-slack-notifier
- name: rsync
  type: registry-image
  source:
    repository: trecnoc/rsync-resource

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines-tasks.git
    branch: master
- name: routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/routing-release
- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bpm-release
- name: dns-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-dns-release
- name: stemcell-xenial
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-xenial-go_agent
- name: stemcell-lite-xenial
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent
- name: stemcell-bionic
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-bionic-go_agent
- name: stemcell-lite-bionic
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-bionic-go_agent    
- name: release-mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/bosh/release
- name: stemcell-mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/bosh/stemcell
- name: notify
  type: slack-notifier
  source:
    url: ((slack_hook))
    disabled: ((slack_disabled))

groups:
- name: releases
  jobs:
  - mirror-routing-release
  - mirror-bpm-release
  - mirror-dns-release
- name: stemcells
  jobs:
  - mirror-stemcell-xenial
  - mirror-stemcell-lite-xenial
  - mirror-stemcell-bionic
  - mirror-stemcell-lite-bionic

jobs:
- name: mirror-routing-release
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: routing-release
      trigger: true
  - task: rename-release
    file: pipeline-tasks/rename-bosh-io-release.yml
    input_mapping:
      release-input: routing-release
  - put: release-mirror
    params:
      sub_dir: release-output
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: routing-release
    params:
      INPUT_TYPE: bosh_io_release
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-bpm-release
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: bpm-release
      trigger: true
  - task: rename-release
    file: pipeline-tasks/rename-bosh-io-release.yml
    input_mapping:
      release-input: bpm-release
  - put: release-mirror
    params:
      sub_dir: release-output
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: bpm-release
    params:
      INPUT_TYPE: bosh_io_release
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-dns-release
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: dns-release
      trigger: true
  - task: rename-release
    file: pipeline-tasks/rename-bosh-io-release.yml
    input_mapping:
      release-input: dns-release
  - put: release-mirror
    params:
      sub_dir: release-output
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: dns-release
    params:
      INPUT_TYPE: bosh_io_release
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-stemcell-xenial
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: stemcell-xenial
      trigger: true
      params:
        preserve_filename: true
  - put: stemcell-mirror
    params:
      sub_dir: stemcell-xenial
      include: "*.tgz"
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: stemcell-xenial
    params:
      INPUT_TYPE: bosh_io_stemcell
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-stemcell-lite-xenial
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: stemcell-lite-xenial
      trigger: true
      params:
        preserve_filename: true
  - put: stemcell-mirror
    params:
      sub_dir: stemcell-lite-xenial
      include: "*.tgz"
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: stemcell-lite-xenial
    params:
      INPUT_TYPE: bosh_io_stemcell
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-stemcell-bionic
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: stemcell-bionic
      trigger: true
      params:
        preserve_filename: true
  - put: stemcell-mirror
    params:
      sub_dir: stemcell-bionic
      include: "*.tgz"
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: stemcell-bionic
    params:
      INPUT_TYPE: bosh_io_stemcell
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-stemcell-lite-bionic
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: stemcell-lite-bionic
      trigger: true
      params:
        preserve_filename: true
  - put: stemcell-mirror
    params:
      sub_dir: stemcell-lite-bionic
      include: "*.tgz"
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: stemcell-lite-bionic
    params:
      INPUT_TYPE: bosh_io_stemcell
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
