---
resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier
- name: rsync
  type: docker-image
  source:
    repository: trecnoc/rsync-resource

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines-tasks.git
    branch: master
- name: doomsday-release
  type: github-release
  source:
    owner: doomsday-project
    repository: doomsday-boshrelease
    access_token: ((github_access_token))
- name: doomsday-cli
  type: github-release
  source:
    owner: doomsday-project
    repository: doomsday
    access_token: ((github_access_token))
- name: release-mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/bosh/release
- name: cli-mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/bosh/doomsday
- name: notify
  type: slack-notifier
  source:
    url: ((slack_hook))
    disabled: ((slack_disabled))

jobs:
- name: mirror-doomsday-release
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: doomsday-release
      trigger: true
  - task: copy-release
    file: pipeline-tasks/copy-github-release.yml
    input_mapping:
      release-input: doomsday-release
    params:
      SKIP_VERSION_SUBDIR: true
      RELEASE_NOTE_PREFIX: "doomsday"
  - put: release-mirror
    params:
      sub_dir: artifacts
  - task: generate-notification
    file: pipeline-tasks/generate-notification.yml
    input_mapping:
      content-input: doomsday-release
    params:
      INPUT_TYPE: doomsday_bosh
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-doomsday-cli
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: doomsday-cli
      trigger: true
      params:
        globs:
          - "doomsday-linux*"
  - task: copy-release
    file: pipeline-tasks/copy-github-release.yml
    input_mapping:
      release-input: doomsday-cli
  - put: cli-mirror
    params:
      sub_dir: artifacts
  - task: generate-notification
    file: pipeline-tasks/generate-notification.yml
    input_mapping:
      content-input: doomsday-cli
    params:
      INPUT_TYPE: doomsday_cli
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
