---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: doomsday-cli-release
  type: github-release
  source:
    owner: doomsday-project
    repository: doomsday
    access_token: ((github_access_token))
- name: doomsday-bosh-release
  type: github-release
  source:
    owner: doomsday-project
    repository: doomsday-boshrelease
    access_token: ((github_access_token))
- name: routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release
- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bpm-release
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-xenial-go_agent
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-cli
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: doomsday-cli-release
      trigger: true
      params:
        globs:
          - doomsday-linux
    - task: process-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
          - name: pipelines-repo
          - name: doomsday-cli-release
        outputs:
          - name: doomsday-cli
        run:
          path: pipelines-repo/scripts/copy-github-release.sh
          args:
            - doomsday-cli-release
            - doomsday-cli
            - doomsday
            - true
    - task: transfer-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
          - name: pipelines-repo
          - name: doomsday-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
            - ((rsync_server))
            - ((rsync_user))
            - ((rsync_key_base64))
            - doomsday-cli
            - /data/repo/bosh
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Doomsday CLI release
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed new Doomsday CLI release
- name: fetch-bosh-release
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: doomsday-bosh-release
      trigger: true
    - task: process-bosh-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: doomsday-bosh-release
        outputs:
        - name: doomsday-bosh
        run:
          path: pipelines-repo/scripts/copy-github-release.sh
          args:
          - doomsday-bosh-release
          - doomsday-bosh
          - doomsday
    - task: transfer-bosh-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: doomsday-bosh
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - doomsday-bosh
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Doomsday Bosh release
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed new Doomsday Bosh release
- name: fetch-routing
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: doomsday-bosh-release
      passed:
        - fetch-bosh-release
      trigger: true
    - get: routing-release
    - task: process-routing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: routing-release
        outputs:
        - name: routing-release-output
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - routing-release
          - routing-release-output
          - routing-release
    - task: transfer-routing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: routing-release-output
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - routing-release-output
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process latest Routing release
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed latest Routing release
- name: fetch-bpm
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: doomsday-bosh-release
      passed:
        - fetch-bosh-release
      trigger: true
    - get: bpm-release
    - task: process-bpm
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: bpm-release
        outputs:
        - name: bpm-release-output
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - bpm-release
          - bpm-release-output
          - bpm-release
    - task: transfer-bpm
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: bpm-release-output
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - bpm-release-output
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process latest BPM release
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed latest BPM release
- name: fetch-stemcell
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: doomsday-bosh-release
      passed:
        - fetch-bosh-release
      trigger: true
    - get: stemcell
      params:
        preserve_filename: true
    - task: process-stemcell
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: stemcell
        outputs:
        - name: stemcell-output
        run:
          path: pipelines-repo/scripts/copy-bosh-io-stemcell.sh
          args:
          - stemcell
          - stemcell-output
    - task: transfer-stemcell
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: stemcell-output
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - stemcell-output
          - /data/repo/bosh/stemcell
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process latest Stemcell
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed latest Stemcell
