---
resource_types:
  - name: slack-notifier
    type: docker-image
    source:
      repository: mockersf/concourse-slack-notifier
  - name: rsync
    type: docker-image
    source:
      repository: trecnoc/rsync-resource

resources:
  - name: pipeline-tasks
    type: git
    source:
      uri: https://github.com/trecnoc/concourse-pipelines-tasks.git
      branch: master
  - name: logsearch-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/logsearch-boshrelease.git
      tag_filter: v*
  - name: alerting-plugin
    type: github-release
    source:
      owner: opendistro-for-elasticsearch
      repository: alerting
      access_token: ((github_access_token))
  - name: alerting-plugin-1.9.0.0
    type: github-release
    source:
      owner: opendistro-for-elasticsearch
      repository: alerting
      access_token: ((github_access_token))
      tag_filter: "v(1.9.0.0)"
  - name: alerting-plugin-1.8.0.0
    type: github-release
    source:
      owner: opendistro-for-elasticsearch
      repository: alerting
      access_token: ((github_access_token))
      tag_filter: "v(1.8.0.0)"
  - name: alerting-plugin-1.7.0.0
    type: github-release
    source:
      owner: opendistro-for-elasticsearch
      repository: alerting
      access_token: ((github_access_token))
      tag_filter: "v(1.7.0.0)"
  - name: bosh-mirror
    type: rsync
    source:
      server: ((rsync_server))
      username: ((rsync_user))
      private_key: ((rsync_key))
      base_dir: /data/repo/bosh/release
  - name: plugins-mirror
    type: rsync
    source:
      server: ((rsync_server))
      username: ((rsync_user))
      private_key: ((rsync_key))
      base_dir: /data/repo/es_plugins
  - name: notify
    type: slack-notifier
    source:
      url: ((slack_hook))
      disabled: ((slack_disabled))

groups:
  - name: logsearch
    jobs:
      - mirror-logsearch-releases
  - name: plugins
    jobs:
      - mirror-alerting-plugin
  - name: old-plugins
    jobs:
      - mirror-alerting-plugin-1.9.0.0
      - mirror-alerting-plugin-1.8.0.0
      - mirror-alerting-plugin-1.7.0.0

jobs:
  - name: mirror-logsearch-releases
    build_log_retention:
      days: 7
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
          - get: pipeline-tasks
          - get: logsearch-deployment
            trigger: true
      - task: generate-manifest
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
          inputs:
            - name: logsearch-deployment
          outputs:
            - name: manifest
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e
                set -o pipefail

                printf "Generating manifest for Logsearch Bosh deployment version %s\n" $(cat logsearch-deployment/.git/ref)
                printf "Excluding BPM and Routing releases"

                cat << EOF > remove-unnecessary-releases.yml
                ---
                - type: remove
                  path: /releases/name=bpm?
                - type: remove
                  path: /releases/name=routing?
                EOF

                bosh int logsearch-deployment/deployment/logsearch-deployment.yml \
                  -o logsearch-deployment/deployment/operations/cloudfoundry.yml \
                  -o remove-unnecessary-releases.yml > manifest/manifest.yml
      - task: download-releases
        file: pipeline-tasks/download-releases-from-manifest.yml
      - put: bosh-mirror
        params:
          sub_dir: releases
      - task: generate-notification
        file: pipeline-tasks/generate-mirrored-notification.yml
        input_mapping:
          content-input: logsearch-deployment
        params:
          INPUT_TYPE: generic
          LABEL: "logsearch deployment"
    on_success:
      put: notify
      params:
        alert_type: success
        mode: concise
        message_file: notification/message.txt
    on_failure:
      put: notify
      params:
        alert_type: failed
        mode: normal
  - name: mirror-alerting-plugin
    build_log_retention:
      days: 7
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
          - get: pipeline-tasks
          - get: alerting-plugin
            trigger: true
            params:
              globs:
                - "*.zip"
      - task: copy-release
        file: pipeline-tasks/copy-github-release.yml
        input_mapping:
          release-input: alerting-plugin
      - put: plugins-mirror
        params:
          sub_dir: artifacts
      - task: generate-notification
        file: pipeline-tasks/generate-mirrored-notification.yml
        input_mapping:
          content-input: alerting-plugin
        params:
          INPUT_TYPE: generic
          LABEL: "opendistro alerting plugin"
    on_success:
      put: notify
      params:
        alert_type: success
        mode: concise
        message_file: notification/message.txt
    on_failure:
      put: notify
      params:
        alert_type: failed
        mode: normal
  # Once a successfull mirroring is done this can be deleted
  - name: mirror-alerting-plugin-1.9.0.0
    build_log_retention:
      days: 7
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
          - get: pipeline-tasks
          - get: alerting-plugin-1.9.0.0
            trigger: true
            params:
              globs:
                - "*.zip"
      - task: copy-release
        file: pipeline-tasks/copy-github-release.yml
        input_mapping:
          release-input: alerting-plugin-1.9.0.0
      - put: plugins-mirror
        params:
          sub_dir: artifacts
      - task: generate-notification
        file: pipeline-tasks/generate-mirrored-notification.yml
        input_mapping:
          content-input: alerting-plugin-1.9.0.0
        params:
          INPUT_TYPE: generic
          LABEL: "opendistro alerting plugin"
    on_success:
      put: notify
      params:
        alert_type: success
        mode: concise
        message_file: notification/message.txt
    on_failure:
      put: notify
      params:
        alert_type: failed
        mode: normal
  # Once a successfull mirroring is done this can be deleted
  - name: mirror-alerting-plugin-1.8.0.0
    build_log_retention:
      days: 7
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
          - get: pipeline-tasks
          - get: alerting-plugin-1.8.0.0
            trigger: true
            params:
              globs:
                - "*.zip"
      - task: copy-release
        file: pipeline-tasks/copy-github-release.yml
        input_mapping:
          release-input: alerting-plugin-1.8.0.0
      - put: plugins-mirror
        params:
          sub_dir: artifacts
      - task: generate-notification
        file: pipeline-tasks/generate-mirrored-notification.yml
        input_mapping:
          content-input: alerting-plugin-1.8.0.0
        params:
          INPUT_TYPE: generic
          LABEL: "opendistro alerting plugin"
    on_success:
      put: notify
      params:
        alert_type: success
        mode: concise
        message_file: notification/message.txt
    on_failure:
      put: notify
      params:
        alert_type: failed
        mode: normal
  # Once a successfull mirroring is done this can be deleted
  - name: mirror-alerting-plugin-1.7.0.0
    build_log_retention:
      days: 7
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
          - get: pipeline-tasks
          - get: alerting-plugin-1.7.0.0
            trigger: true
            params:
              globs:
                - "*.zip"
      - task: copy-release
        file: pipeline-tasks/copy-github-release.yml
        input_mapping:
          release-input: alerting-plugin-1.7.0.0
      - put: plugins-mirror
        params:
          sub_dir: artifacts
      - task: generate-notification
        file: pipeline-tasks/generate-mirrored-notification.yml
        input_mapping:
          content-input: alerting-plugin-1.7.0.0
        params:
          INPUT_TYPE: generic
          LABEL: "opendistro alerting plugin"
    on_success:
      put: notify
      params:
        alert_type: success
        mode: concise
        message_file: notification/message.txt
    on_failure:
      put: notify
      params:
        alert_type: failed
        mode: normal
