---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: mattermost-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/mattermost-boshrelease
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-mattermost
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: mattermost-boshrelease
      trigger: true
    - task: process-mattermost
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: mattermost-boshrelease
        outputs:
        - name: releases
        run:
          path: pipelines-repo/scripts/process-mattermost.sh
          args:
          - pipelines-repo/scripts/copy-bosh-io-release.sh
          - mattermost-boshrelease
          - releases
    - task: transfer-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":skull_and_crossbones:"
        text: $BUILD_JOB_NAME job failed
    on_success:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":thumbsup:"
        text: $BUILD_JOB_NAME job succeeded