---
resource_types:
- name: slack-notifier
  type: registry-image
  source:
    repository: mockersf/concourse-slack-notifier
- name: rsync
  type: registry-image
  source:
    repository: trecnoc/rsync-resource

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines-tasks.git
    branch: master
- name: mattermost-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/mattermost-boshrelease
- name: mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/bosh/release
- name: notify
  type: slack-notifier
  source:
    url: ((slack_hook))
    disabled: ((slack_disabled))

jobs:
- name: mirror-mattermost-release
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: mattermost-release
      trigger: true
  - task: rename-release
    file: pipeline-tasks/rename-bosh-io-release.yml
    input_mapping:
      release-input: mattermost-release
    params:
      CUSTOM_FILENAME_PREFIX: mattermost-boshrelease
  - put: mirror
    params:
      sub_dir: release-output
  - task: generate-notification
    file: pipeline-tasks/generate-mirrored-notification.yml
    input_mapping:
      content-input: mattermost-release
    params:
      INPUT_TYPE: bosh_io_release
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
