---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: mrsixw/concourse-rsync-resource
    tag: latest

resources:
- name: pipelines
  type: git
  source:
    uri: https://github.com/stevesmatts/concourse-pipelines.git
    branch: master
- name: mattermost-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/mattermost-boshrelease

jobs:
- name: fetch-mattermost
  public: true
  plan:
  - get: pipelines
  - get: mattermost-boshrelease
    trigger: true
  - task: fetch-mattermost
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: pipelines
      - name: mattermost-boshrelease
        path: incoming-release
      run:
        path: pipelines/scripts/output-bosh-io-release.sh
        args:
        - mattermost-boshrelease
        - 'bosh_io'