---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: mattermost-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/mattermost-boshrelease
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-xenial-go_agent
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-mattermost
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: mattermost-boshrelease
      trigger: true
    - task: process-mattermost
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: mattermost-boshrelease
        outputs:
        - name: releases
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - mattermost-boshrelease
          - releases
          - mattermost-boshrelease
    - task: transfer-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Mattermost release
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed new Mattermost release
- name: fetch-stemcell
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: mattermost-boshrelease
      passed:
        - fetch-mattermost
      trigger: true
    - get: stemcell
      params:
        preserve_filename: true
    - task: process-stemcell
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: stemcell
        outputs:
        - name: stemcell-output
        run:
          path: pipelines-repo/scripts/copy-bosh-io-stemcell.sh
          args:
          - stemcell
          - stemcell-output
    - task: transfer-stemcell
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: stemcell-output
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - stemcell-output
          - /data/repo/bosh/stemcell
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process latest Stemcell
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed latest Stemcell
