---
resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier
- name: rsync
  type: docker-image
  source:
    repository: trecnoc/rsync-resource

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines-tasks.git
    branch: master
- name: minio-release
  type: bosh-io-release
  source:
    repository: minio/minio-boshrelease
- name: mc-release
  type: github-release
  source:
    owner: minio
    repository: mc
    access_token: ((github_access_token))
- name: release-mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/bosh/release
- name: cli-mirror
  type: rsync
  source:
    server: ((rsync_server))
    username: ((rsync_user))
    private_key: ((rsync_key))
    base_dir: /data/repo/minio
- name: notify
  type: slack-notifier
  source:
    url: ((slack_hook))
    disabled: ((slack_disabled))

jobs:
- name: mirror-minio-release
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: minio-release
      trigger: true
  - task: rename-release
    file: pipeline-tasks/rename-bosh-io-release.yml
    input_mapping:
      release-input: minio-release
    params:
      CUSTOM_FILENAME_PREFIX: minio-boshrelease
  - put: release-mirror
    params:
      sub_dir: release-output
  - task: generate-notification
    file: pipeline-tasks/generate-notification.yml
    input_mapping:
      content-input: minio-release
    params:
      INPUT_TYPE: bosh_io_release
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
- name: mirror-minio-cli
  build_log_retention:
    days: 7
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: mc-release
      trigger: true
  - task: download-cli
    file: pipeline-tasks/download-mc-cli.yml
  - put: cli-mirror
    params:
      sub_dir: mc-cli
  - task: generate-notification
    file: pipeline-tasks/generate-notification.yml
    input_mapping:
      content-input: mc-release
    params:
      INPUT_TYPE: minio_cli
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: normal
