---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: minio-boshrelease
  type: bosh-io-release
  source:
    repository: minio/minio-boshrelease
- name: mc-release
  type: github-release
  source:
    owner: minio
    repository: mc
    access_token: ((github_access_token))
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-minio
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: minio-boshrelease
      trigger: true
    - task: process-minio
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: minio-boshrelease
        outputs:
        - name: releases
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - minio-boshrelease
          - releases
          - minio-boshrelease
    - task: transfer-minio
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Minio release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed new Minio release
        silent: true
- name: fetch-minio-cli
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: mc-release
      trigger: true
    - task: process-minio-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: mc-release
        outputs:
        - name: mc-cli
        run:
          path: pipelines-repo/scripts/process-minio-cli.sh
          args:
          - mc-release
          - mc-cli
    - task: transfer-minio-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: mc-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - mc-cli
          - /data/repo/minio
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Minio CLI release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed new Minio CLI release
        silent: true
