---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: cf-mysql-deployment-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-mysql-deployment.git
    tag_filter: v*
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-mysql
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-mysql-deployment-repo
      trigger: true
    - task: process-mysql
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-mysql-deployment-repo
        outputs:
        - name: releases
        run:
          path: pipelines-repo/scripts/process-cf-mysql-deployment-repo.sh
          args:
          - pipelines-repo/scripts/fetch-bosh-releases-from-manifest.sh
          - cf-mysql-deployment-repo
          - pipelines-repo/scripts/ops_files
          - releases
    - task: transfer-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new MySQL release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed new MySQL release
        silent: true
