---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: mrsixw/concourse-rsync-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/stevesmatts/concourse-pipelines.git
    branch: master
- name: mysql-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release
- name: transfer-releases
  type: rsync-resource
  source:
    server: ((rsync_server))
    base_dir: /data/repo/bosh_io_releases
    user : ((rsync_user))
    private_key: ((rsync_key))
    disable_version_path: true

jobs:
- name: fetch-mysql
  public: true
  build_logs_to_retain: 1
  plan:
  - get: pipelines-repo
  - get: mysql-boshrelease
    trigger: true
  - task: fetch-mysql
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: starkandwayne/concourse}
      inputs:
      - name: pipelines-repo
      - name: mysql-boshrelease
        path: incoming-release
      outputs:
      - name: release
      run:
        path: pipelines-repo/scripts/copy-bosh-io-release.sh
        args:
        - incoming-release
        - release
        - cf-mysql-release
  - put: transfer-releases
    params: {
      "sync_dir" : "release",
      "rsync_opts" : ["-Pav", "--ignore-existing"]
    }