---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: mrsixw/concourse-rsync-resource
    tag: latest
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/stevesmatts/concourse-pipelines.git
    branch: master
- name: cf-rabbitmq-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-release
- name: cf-rabbitmq-multitenant-broker-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-multitenant-broker-release
- name: cf-cli-release
  type: bosh-io-release
  source:
    repository: bosh-packages/cf-cli-release
- name: transfer-releases
  type: rsync-resource
  source:
    server: ((rsync_server))
    base_dir: /data/repo/bosh_io_releases
    user : ((rsync_user))
    private_key: ((rsync_key))
    disable_version_path: true
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-rabbitmq
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-rabbitmq-release
      trigger: true
    - get: cf-rabbitmq-multitenant-broker-release
      trigger: true
    - get: cf-cli-release
      trigger: true
    - task: fetch-rabbitmq
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-rabbitmq-release
          path: incoming-release
        outputs:
        - name: release
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - incoming-release
          - release
          - cf-rabbitmq-release
    - put: transfer-releases
      params: {
        "sync_dir" : "release",
        "rsync_opts" : ["-Pav", "--ignore-existing"]
      }
    - task: fetch-rabbitmq-broker
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-rabbitmq-multitenant-broker-release
          path: incoming-release
        outputs:
        - name: release
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - incoming-release
          - release
          - cf-rabbitmq-multitenant-broker-release
    - put: transfer-releases
      params: {
        "sync_dir" : "release",
        "rsync_opts" : ["-Pav", "--ignore-existing"]
      }
    - task: fetch-cf-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-cli-release
          path: incoming-release
        outputs:
        - name: release
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - incoming-release
          - release
          - cf-cli-release
    - put: transfer-releases
      params: {
        "sync_dir" : "release",
        "rsync_opts" : ["-Pav", "--ignore-existing"]
      }
    on_failure:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":skull_and_crossbones:"
        text: $BUILD_JOB_NAME job failed
    on_success:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":thumbsup:"
        text: $BUILD_JOB_NAME job succeeded