---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: cf-rabbitmq-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-release
- name: cf-rabbitmq-multitenant-broker-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-multitenant-broker-release
- name: cf-rabbitmq-smoke-tests-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-smoke-tests-release
- name: cf-cli-release
  type: bosh-io-release
  source:
    repository: bosh-packages/cf-cli-release
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-rabbitmq
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-rabbitmq-release
      trigger: true
    - task: process-rabbitmq
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-rabbitmq-release
        outputs:
        - name: rabbitmq-releases
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - cf-rabbitmq-release
          - rabbitmq-releases
          - cf-rabbitmq-release
    - task: transfer-rabbitmq-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: rabbitmq-releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - rabbitmq-releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new RabbitMQ release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed new RabbitMQ release
        silent: true
- name: fetch-rabbitmq-broker
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-rabbitmq-release
      passed:
        - fetch-rabbitmq
      trigger: true
    - get: cf-rabbitmq-multitenant-broker-release
    - task: process-rabbitmq-broker
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-rabbitmq-multitenant-broker-release
        outputs:
        - name: broker-release
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - cf-rabbitmq-multitenant-broker-release
          - broker-release
          - cf-rabbitmq-multitenant-broker-release
    - task: transfer-rabbitmq-broker
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: broker-release
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - broker-release
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new RabbitMQ Broker release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed new RabbitMQ Broker release
        silent: true
- name: fetch-rabbitmq-smoke-tests
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-rabbitmq-release
      passed:
        - fetch-rabbitmq
      trigger: true
    - get: cf-rabbitmq-smoke-tests-release
    - task: process-rabbitmq-smoke-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-rabbitmq-smoke-tests-release
        outputs:
        - name: smoke-tests-release
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - cf-rabbitmq-smoke-tests-release
          - smoke-tests-release
          - cf-rabbitmq-smoke-tests-release
    - task: transfer-rabbitmq-smoke-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: smoke-tests-release
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - smoke-tests-release
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process latest RabbitMQ Smoke Tests release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed latest RabbitMQ Smoke Tests release
        silent: true
- name: fetch-cf-cli
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-rabbitmq-release
      passed:
        - fetch-rabbitmq
      trigger: true
    - get: cf-cli-release
    - task: process-cf-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-cli-release
        outputs:
        - name: cf-cli-release-output
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - cf-cli-release
          - cf-cli-release-output
          - cf-cli-release
    - task: transfer-cf-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: cf-cli-release-output
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - cf-cli-release-output
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process latest CF-CLI release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed latest CF-CLI release
        silent: true
