---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: cf-rabbitmq-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-release
- name: cf-rabbitmq-multitenant-broker-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/cf-rabbitmq-multitenant-broker-release
- name: cf-cli-release
  type: bosh-io-release
  source:
    repository: bosh-packages/cf-cli-release
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-rabbitmq
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: cf-rabbitmq-release
      trigger: true
    - get: cf-rabbitmq-multitenant-broker-release
      trigger: true
    - get: cf-cli-release
      trigger: true
    - task: process-rabbitmq
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: cf-rabbitmq-release
        - name: cf-rabbitmq-multitenant-broker-release
        - name: cf-cli-release
        outputs:
        - name: releases
        run:
          path: pipelines-repo/scripts/process-rabbitmq.sh
          args:
          - pipelines-repo/scripts/copy-bosh-io-release.sh
          - cf-rabbitmq-release
          - cf-rabbitmq-multitenant-broker-release
          - cf-cli-release
          - releases
    - task: transfer-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new releases
    on_success:
      put: notify
      params:
        username: $BUILD_PIPELINE_NAME
        icon_emoji: ":thumbsup:"
        text: Successfully processed new releases
