---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: postgres-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-postgres
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: postgres-release
      trigger: true
    - task: process-postgres
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: postgres-release
        outputs:
        - name: postgres-releases
        run:
          path: pipelines-repo/scripts/copy-bosh-io-release.sh
          args:
          - postgres-release
          - postgres-releases
          - postgres-release
    - task: transfer-postgres-releases
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: postgres-releases
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - postgres-releases
          - /data/repo/bosh/release
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Postgres release
        silent: true
    on_success:
      put: notify
      params:
        text: Successfully processed new Postgres release
        silent: true
