---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pipelines-repo
  type: git
  source:
    uri: https://github.com/trecnoc/concourse-pipelines.git
    branch: master
- name: bosh-cli-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-cli
    access_token: ((github_access_token))
- name: credhub-cli-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: credhub-cli
    access_token: ((github_access_token))
- name: bbr-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github_access_token))
- name: mc-release
  type: github-release
  source:
    owner: minio
    repository: mc
    access_token: ((github_access_token))
- name: cf-mgmt-release
  type: github-release
  source:
    owner: pivotalservices
    repository: cf-mgmt
    access_token: ((github_access_token))
- name: notify
  type: slack-notification
  source:
    url: ((slack_hook))
    disable: ((slack_disabled))

jobs:
- name: fetch-tools
  public: true
  build_logs_to_retain: 1
  plan:
  - do:
    - get: pipelines-repo
    - get: bosh-cli-release
      trigger: true
      params:
        globs:
        - "bosh-cli-*-linux-amd64"
    - get: credhub-cli-release
      trigger: true
      params:
        globs:
        - "credhub-linux-*.tgz"
    - get: bbr-release
      trigger: true
      params:
        globs:
        - "bbr-*.tar"
    - get: mc-release
      trigger: true
    - get: cf-mgmt-release
      trigger: true
      params:
        globs:
        - "*-linux"
    - task: process-tools
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: pipelines-repo
        - name: bosh-cli-release
        - name: credhub-cli-release
        - name: bbr-release
        - name: mc-release
        - name: cf-mgmt-release
        outputs:
        - name: bosh-cli
        - name: credhub-cli
        - name: bbr-cli
        - name: mc-cli
        - name: cf-mgmt-cli
        run:
          path: pipelines-repo/scripts/process-tools.sh
          args:
          - pipelines-repo/scripts/copy-github-release.sh
          - bosh-cli-release
          - credhub-cli-release
          - bbr-release
          - mc-release
          - cf-mgmt-release
    - task: transfer-bosh-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: bosh-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - bosh-cli
          - /data/repo/bosh
    - task: transfer-credhub-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: credhub-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - credhub-cli
          - /data/repo/bosh/credhub
    - task: transfer-bbr-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: bbr-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - bbr-cli
          - /data/repo/bosh/bbr
    - task: transfer-mc-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: mc-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - mc-cli
          - /data/repo/minio
    - task: transfer-cf-mgmt-cli
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: trecnoc/concourse-rsync}
        inputs:
        - name: pipelines-repo
        - name: cf-mgmt-cli
        run:
          path: pipelines-repo/scripts/rsync.sh
          args:
          - ((rsync_server))
          - ((rsync_user))
          - ((rsync_key_base64))
          - cf-mgmt-cli
          - /data/repo/bosh/cf-mgmt
    on_failure:
      put: notify
      params:
        icon_emoji: ":skull_and_crossbones:"
        text: Failed to process new Bosh Tools releases
    on_success:
      put: notify
      params:
        icon_emoji: ":thumbsup:"
        text: Successfully processed new Bosh Tools releases
