---
resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier
- name: nexus
  type: docker-image
  source:
    repository: trecnoc/nexus-resource
    tag: latest

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: ((tasks-repository))
    branch: ((tasks-branch))
- name: buildpack-artifact
  type: nexus
  source:
    url: ((nexus-url))
    username: ((nexus-username))
    password: ((nexus-password))
    repository: ((nexus-repository))
    group: ((nexus-buildpack-group))
    regexp: ((nexus-buildpack-regexp))
    timeout: ((nexus-timeout))
- name: buildpack-repo
  type: git
  source:
    uri: ((buildpack-git-repository))
    branch: ((buildpack-git-branch))
    username: ((buildpack-git-username))
    password: ((buildpack-git-password))
- name: bosh-release
  type: nexus
  source:
    url: ((nexus-url))
    username: ((nexus-username))
    password: ((nexus-password))
    repository: ((nexus-repository))
    group: ((nexus-bosh-group))
    regexp: ((nexus-bosh-regexp))
    timeout: ((nexus-timeout))
- name: notify
  type: slack-notifier
  source:
    url: ((slack-webhook))

jobs:
- name: create-bosh-release
  build_log_retention:
    builds: 10
    minimum_succeeded_builds: 1
  plan:
  - in_parallel:
    - get: buildpack-artifact
      trigger: true
    - get: buildpack-repo
    - get: pipeline-tasks
  - task: bump-buildpack
    file: pipeline-tasks/bump-blob.yml
    params:
      CI_BOT_USER: ((bot-user))
      CI_BOT_EMAIL: ((bot-email))
      ACCESS_KEY_ID: ((bucket-access-key))
      SECRET_KEY: ((bucket-secret-key))
      BLOB_NAME: ((buildpack-blob-name))
      BLOB_REGEX: ((buildpack-blob-regexp))
    input_mapping:
      blob-input: buildpack-artifact
      repository-input: buildpack-repo
    output_mapping:
      repository-output: bumped-repository
  - task: create-release
    file: pipeline-tasks/create-release.yml
    params:
      CI_BOT_USER: ((bot-user))
      CI_BOT_EMAIL: ((bot-email))
      ACCESS_KEY_ID: ((bucket-access-key))
      SECRET_KEY: ((bucket-secret-key))
    input_mapping:
      repository-input: bumped-repository
      version-input: buildpack-artifact
    output_mapping:
      repository-output: final-repository
  - put: buildpack-repo
    params:
      repository: final-repository
      rebase: true
  - put: bosh-release
    params:
      file: release-tarball/*.tgz
  on_success:
    put: notify
    params:
      alert_type: success
      mode: concise
      message_file: notification-output/message.txt
  on_failure:
    put: notify
    params:
      alert_type: failed
      mode: concise
      message: Failed building ((buildpack-blob-name)) Bosh release
