#!/usr/bin/env bash

set -e
set -o pipefail

if [[ "$#" -ne 1 ]]; then
  echo "Invalid parameter, requires the concourse target"
  exit 1
fi

if ! command -v fly > /dev/null 2>&1; then
  echo "fly must be installed before running this script!"
  exit 1
fi

scriptDir=$(cd $(dirname $0) && pwd)
concourse_target=$1

${scriptDir}/reconfigure-pipeline ${concourse_target} binary-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} dotnet-core-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} go-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} java-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} nginx-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} nodejs-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} php-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} python-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} r-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} ruby-buildpack
${scriptDir}/reconfigure-pipeline ${concourse_target} staticfile-buildpack
